[project]
name = "zadanie-domowe-6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.14.0",
    "scipy>=1.16.3",
]
